### PR TITLE
Issue17-TransitionViewNewCR

### PR DESCRIPTION
**Pull request by ArCiGo**
* Waiting for approval

### CODE REVIEW

**Comment by geoperez** [comment]
Please include a screenshot.

**Comment by ArCiGo** [comment]
screenshot_3

**Comment by geoperez** [comment]
@mariodivece what do you think?

**Comment by geoperez** [comment]
@ArCiGoUnoSquare I got some conflicts, can you tell me what lines are for merge?

**Comment by ArCiGo** [comment]
@geoperez Don't delete the branch. I'm adding the OFF functionality.

**Comment by geoperez** [comment]
Why are you adding another functionality in the same branch?

**Pull request merged**
