### PR TITLE
Issue23-OFF functionality

### PR DESCRIPTION
**Pull request by ArCiGo**
* Waiting for approval

### CODE REVIEW

**Comment by geoperez** [comment]
Can you include a screenshot?

**Comment by ArCiGo** [comment]
We added a button instead of `<Switch />`. When the button is clicked, the button changes to disable. We didn't use a `<Switch />` component because the led strip is always on.

screenshot_3
screenshot_3

**Comment by geoperez** [comment]
Use a switch .
https://material-ui-next.com/demos/selection-controls/#switches

**Comment by ArCiGo** [comment]
screenshot_2
screenshot_3

**Pull request merged**
